openapi: 3.0.0
info:
  title: "Ip Management"
  description: "An api for ip management"
  version: 1.0.0

servers:
  - url: http://localhost:8080/

paths:
  /api/login:
    post:
      tags:
        - "Auth"
      description: "Authenticate User"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: "test@email.com"
                password:
                  type: string
                  example: "password"

      responses:
        200:
          description: Returns User Token
          content:
            application/json:
              example:
                "data":
                  {
                    "id": 1,
                    "name": "normal user",
                    "email": "normal@user.com",
                    "token": "1|CRDiVYpEuUFcl7TpshUTbRgXc7CZKe2s3VYQTLhj",
                    "created_at": "2023-07-02T04:17:50.000000Z",
                    "updated_at": "2023-07-02T04:17:50.000000Z",
                  }

  /api/ip-address:
    get:
      tags:
        - "IP Address"
      description: "Fech All Ip Addresses wih Pagination"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                per_page:
                  type: integer
                  example: 10
      responses:
        200:
          description: Returns User Token
          content:
            application/json:
              example:
                {
                  "data":
                    [
                      {
                        "id": 1,
                        "ip_address": "192.0.2.1",
                        "labels":
                          [
                            {
                              "id": 1,
                              "ip_address_id": 1,
                              "user":
                                {
                                  "id": 1,
                                  "ip_address": "192.0.2.1",
                                  "created_at": "2023-07-03T05:20:40.000000Z",
                                  "updated_at": "2023-07-03T05:20:40.000000Z",
                                },
                              "label": "HR Dept",
                              "created_at": "2023-07-03T05:20:40.000000Z",
                            },
                          ],
                        "created_at": "2023-07-03T05:20:40.000000Z",
                      },
                      {
                        "id": 2,
                        "ip_address": "192.0.2.12",
                        "labels":
                          [
                            {
                              "id": 2,
                              "ip_address_id": 2,
                              "user":
                                {
                                  "id": 1,
                                  "ip_address": "192.0.2.1",
                                  "created_at": "2023-07-03T05:20:40.000000Z",
                                  "updated_at": "2023-07-03T05:20:40.000000Z",
                                },
                              "label": "HR Dept",
                              "created_at": "2023-07-03T05:23:16.000000Z",
                            },
                          ],
                        "created_at": "2023-07-03T05:23:16.000000Z",
                      },
                    ],
                  "links":
                    {
                      "first": "http://localhost:8080/api/ip-address?page=1",
                      "last": "http://localhost:8080/api/ip-address?page=1",
                      "prev": null,
                      "next": null,
                    },
                  "meta":
                    {
                      "current_page": 1,
                      "from": 1,
                      "last_page": 1,
                      "links":
                        [
                          {
                            "url": null,
                            "label": "&laquo; Previous",
                            "active": false,
                          },
                          {
                            "url": "http://localhost:8080/api/ip-address?page=1",
                            "label": "1",
                            "active": true,
                          },
                          {
                            "url": null,
                            "label": "Next &raquo;",
                            "active": false,
                          },
                        ],
                      "path": "http://localhost:8080/api/ip-address",
                      "per_page": 10,
                      "to": 2,
                      "total": 2,
                    },
                }
    post:
      tags:
        - "IP Address"
      description: "Add Ip Address and Label"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ip_address:
                  type: string
                  example: "192.0.2.1"
                label:
                  type: string
                  example: "label test"
      responses:
        201:
          description: Returns User Token
          content:
            application/json:
              example:
                {
                  "data":
                    {
                      "id": 1,
                      "ip_address": "192.0.2.1",
                      "labels":
                        [
                          {
                            "id": 1,
                            "user_id": 1,
                            "ip_address_id": 1,
                            "label": "HR Dept",
                            "created_at": "2023-07-02T04:20:29.000000Z",
                            "updated_at": "2023-07-02T04:20:29.000000Z",
                          },
                        ],
                    },
                }

  /api/ip-address/{ip_address_id}/{label_id?}:
    put:
      tags:
        - "IP Address"
      description: "Add Ip Address and Label"
      parameters:
        - in: path
          name: "ip_address_id"
          required: true
          schema:
            type: integer
        - in: path
          name: "label_id"
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ip_address:
                  type: string
                  example: "192.0.2.1"
                label:
                  type: string
                  example: "label test"
      responses:
        200:
          description: Returns User Token
          content:
            application/json:
              example:
                {
                  "data":
                    {
                      "id": 1,
                      "ip_address": "192.0.2.1",
                      "labels":
                        [
                          {
                            "id": 1,
                            "user_id": 1,
                            "ip_address_id": 1,
                            "label": "HR Dept",
                            "created_at": "2023-07-02T04:20:29.000000Z",
                            "updated_at": "2023-07-02T04:20:29.000000Z",
                          },
                        ],
                    },
                }

  /api/labels:
    get:
      tags:
        - "IP Address Labels"
      description: "Add Ip Address and Label"
      parameters:
        - in: query
          name: "per_page"
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Returns User Token
          content:
            application/json:
              example:
                {
                  "data":
                    [
                      {
                        "id": 1,
                        "ip_address_id": 1,
                        "user":
                          {
                            "id": 1,
                            "ip_address": "192.0.2.1",
                            "created_at": "2023-07-03T05:20:40.000000Z",
                            "updated_at": "2023-07-03T05:20:40.000000Z",
                          },
                        "label": "HR Dept",
                        "created_at": "2023-07-03T05:20:40.000000Z",
                      },
                      {
                        "id": 2,
                        "ip_address_id": 2,
                        "user":
                          {
                            "id": 1,
                            "ip_address": "192.0.2.1",
                            "created_at": "2023-07-03T05:20:40.000000Z",
                            "updated_at": "2023-07-03T05:20:40.000000Z",
                          },
                        "label": "HR Dept",
                        "created_at": "2023-07-03T05:23:16.000000Z",
                      },
                      {
                        "id": 3,
                        "ip_address_id": 1,
                        "user":
                          {
                            "id": 1,
                            "ip_address": "192.0.2.1",
                            "created_at": "2023-07-03T05:20:40.000000Z",
                            "updated_at": "2023-07-03T05:20:40.000000Z",
                          },
                        "label": "Data Dept",
                        "created_at": "2023-07-03T05:28:27.000000Z",
                      },
                    ],
                  "links":
                    {
                      "first": "http://localhost:8080/api/labels?page=1",
                      "last": "http://localhost:8080/api/labels?page=1",
                      "prev": null,
                      "next": null,
                    },
                  "meta":
                    {
                      "current_page": 1,
                      "from": 1,
                      "last_page": 1,
                      "links":
                        [
                          {
                            "url": null,
                            "label": "&laquo; Previous",
                            "active": false,
                          },
                          {
                            "url": "http://localhost:8080/api/labels?page=1",
                            "label": "1",
                            "active": true,
                          },
                          {
                            "url": null,
                            "label": "Next &raquo;",
                            "active": false,
                          },
                        ],
                      "path": "http://localhost:8080/api/labels",
                      "per_page": 10,
                      "to": 3,
                      "total": 3,
                    },
                }

  /api/labels/{ip_address_id}:
    post:
      tags:
        - "IP Address Labels"
      description: "Add Ip Address and Label"
      parameters:
        - in: path
          name: "ip_address_id"
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                label:
                  type: string
                  example: "label test"
      responses:
        200:
          description: Returns User Token
          content:
            application/json:
              example:
                {
                  "data":
                    {
                      "id": 3,
                      "ip_address_id": 1,
                      "user":
                        {
                          "id": 1,
                          "ip_address": "192.0.2.1",
                          "created_at": "2023-07-03T05:20:40.000000Z",
                          "updated_at": "2023-07-03T05:20:40.000000Z",
                        },
                      "label": "Data Dept",
                      "created_at": "2023-07-03T05:28:27.000000Z",
                    },
                }
